root: true
extends:
  - "@cordova/eslint-config/node"

plugins:
  - es
  - es5

parserOptions:
  ecmaFeatures:
    impliedStrict: true

overrides:
  - files:
      - tests/specs/**/*.js
    extends:
      - "@cordova/eslint-config/node-tests"
    rules:
      quotes: ["error", "double"]

  - files:
      - www/**/*.js
    extends:
      # ES5
      - "plugin:es5/no-es2015"
      - "@cordova/eslint-config/browser"
    rules:
      quotes: ["error", "double"]
      no-var: 0

rules:
  quotes: ["error", "double"]
